import csv, re
csv.field_size_limit(10_000_000)
patterns = {
 'regalia': r'REGALIA',
 'mayor': r'MAYOR',
 'towncrier': r'TOWN CRIER',
 'civic': r'\bCIVIC\b',
 'beacon': r'BEACON LIGHT|LIGHTING OF|BEACONS',
 'jubilee': r'JUBILEE',
 'coronation': r'CORONATION',
 'pigeon': r'PIGEON',
 'gull': r'\bGULLS?\b|SEAGULL',
 'dog': r'DOG (WASTE|FOUL|POO|BIN)|POOP',
 'allotment': r'ALLOTMENT',
 'clock': r'CLOCK (WIND|REPAIR|MAINT)|TOWN CLOCK',
 'mace_robes': r'\bMACE\b|\bROBES?\b',
 'banquet': r'BANQUET',
 'xmas': r'CHRISTMAS',
 'bunting_flags': r'BUNTING|\bFLAGS\b',
 'war_memorial': r'WAR MEMORIAL',
 'bowling': r'BOWLING GREEN|BOWLS',
 'freedom': r'FREEDOM OF THE',
 'twinning': r'TWINNING|TWIN TOWN',
 'chains': r'CHAIN OF OFFICE|CIVIC CHAIN',
 'bandstand': r'BANDSTAND',
 'maypole': r'MAYPOLE',
 'donkey_etc': r'DONKEY|LLAMA|ALPACA|FALCON|REINDEER',
 'santa': r'\bSANTA\b|GROTTO|FATHER CHRISTMAS',
 'panto': r'PANTO',
 'fireworks': r'FIREWORK',
 'toilets': r'PUBLIC CONVENIENCE|TOILET',
 'cemetery_odd': r'EXHUMATION|GRAVE DIGGING',
 'pest': r'PEST|VERMIN|RODENT',
 'wasps_bees': r'WASP|BEE REMOVAL|BEES',
 'horse': r'STRAY HORSE|HORSE',
 'animal': r'ANIMAL WELFARE|STRAY DOG|DOG WARDEN|CATTLE|SHEEP',
 'witchcraft': r'WITCH|WIZARD|MAGIC',
 'tea': r'\bTEA\b|BISCUIT|REFRESHMENT',
 'queen': r'\bQUEEN\b|ROYAL VISIT',
 'duckhouse': r'DUCK',
 'moat': r'\bMOAT\b',
 'medieval': r'MEDIEVAL|JOUST',
 'morris': r'MORRIS',
 'ghost': r'GHOST|HAUNT',
 'lido': r'\bLIDO\b|PADDLING POOL',
 'hanging_baskets': r'HANGING BASKET|FLORAL DISPLAY|IN BLOOM',
 'roundabout': r'ROUNDABOUT',
 'statue': r'STATUE',
 'plinth': r'PLINTH',
 'gnome': r'GNOME',
 'scarecrow': r'SCARECROW',
 'cheese_food': r'CHEESE|SAUSAGE|PORK PIE',
 'carnival': r'CARNIVAL|\bFETE\b|GALA',
 'crazy_golf': r'CRAZY GOLF|MINI GOLF|PUTTING',
 'beach_hut': r'BEACH HUT',
 'promenade': r'PROMENADE',
 'pier': r'\bPIER\b',
 'bouncy': r'BOUNCY',
 'facepaint': r'FACE PAINT',
 'balloon': r'BALLOON',
 'trophy': r'TROPH(Y|IES)|ENGRAVING',
 'flagpole': r'FLAGPOLE',
 'bins_odd': r'LITTER BIN|BIN LIDS',
 'weed': r'WEED (KILLING|CONTROL|SPRAY)',
 'grass': r'GRASS CUTTING|MOWING',
 'churchyard': r'CLOSED CHURCHYARD',
 'depot': r'SNOW|GRIT|SALT BARN',
 'lord': r'LORD LIEUTENANT|HIGH SHERIFF',
 'ceremonial': r'CEREMONI',
 'ermine': r'ERMINE',
 'garden_party': r'GARDEN PART',
 'honours': r'HONOURS|MBE|OBE',
 'portrait': r'PORTRAIT',
 'flag_days': r'FLAG (RAISING|DAY)',
 'remembrancer': r'REMEMBRANC',
 'beadle': r'BEADLE',
 'verger': r'VERGER',
 'organist': r'ORGANIST',
 'bellringer': r'BELL ?RING',
 'brassband': r'BRASS BAND|BAND CONCERT',
 'punch': r'PUNCH (AND|&) JUDY',
 'ice_cream': r'ICE CREAM',
 'candyfloss': r'CANDY ?FLOSS',
 'funfair': r'FUNFAIR|FAIRGROUND',
 'circus': r'CIRCUS',
 'zoo': r'\bZOO\b',
 'aquarium': r'AQUARIUM',
 'hedgehog': r'HEDGEHOG',
 'bat': r'\bBATS?\b',
 'newt': r'NEWT',
 'badger': r'BADGER',
 'swan': r'SWAN',
 'peacock': r'PEACOCK',
 'squirrel': r'SQUIRREL',
 'mole': r'\bMOLES?\b',
 'rabbit': r'RABBIT',
 'deer': r'\bDEER\b',
 'seal': r'\bSEALS?\b',
 'whale': r'WHALE',
 'jellyfish': r'JELLYFISH',
}
for col in ('expense_type','expense_area'):
    rows = list(csv.DictReader(open(f'{col}_distinct.csv', encoding='utf-8')))
    out = open(f'{col}_candidates.csv','w',newline='',encoding='utf-8')
    w = csv.writer(out)
    w.writerow(['bucket',col,'n_txn','gbp_total','n_publishers','a_publisher'])
    n=0
    for r in rows:
        s = r[col].upper()
        for k,p in patterns.items():
            if re.search(p,s):
                w.writerow([k, r[col], r['n_txn'], r['gbp_total'], r['n_publishers'], r['a_publisher']])
                n+=1
    out.close()
    print(col, len(rows), 'distinct,', n, 'candidate matches')
