import csv, re, sys
csv.field_size_limit(10_000_000)
rows = list(csv.DictReader(open('suppliers_distinct.csv', encoding='utf-8')))
print(len(rows), 'distinct suppliers')

patterns = {
 'llama': r'\bLLAMAS?\b',
 'alpaca': r'\bALPACAS?\b',
 'falconry': r'FALCONRY|\bFALCONS?\b|\bBIRDS? OF PREY\b',
 'clairvoyant': r'CLAIRVOY|PSYCHIC|SPIRITUALIST|TAROT|FORTUNE TELL',
 'brass_band': r'BRASS BAND|SILVER BAND|COLLIERY BAND|PIPE BAND',
 'morris': r'MORRIS (DANC|MEN|SIDE)|\bMOLLY DANC',
 'taxidermy': r'TAXIDERM',
 'pest': r'PEST CONTROL|PEST SOLUTIONS|VERMIN|MOLE CATCH|MOLECATCH|RAT CATCH|RATCATCH|\bWASPS?\b|BED ?BUG',
 'towncrier': r'TOWN CRIER|\bBELLMAN\b',
 'donkey': r'\bDONKEYS?\b',
 'owl': r'\bOWLS?\b',
 'ferret': r'\bFERRETS?\b',
 'hedgehog': r'HEDGEHOG',
 'bees': r'\bBEES?\b|BEEKEEP|APIAR',
 'pigeon': r'PIGEON',
 'gull': r'\bGULLS?\b|SEAGULL',
 'swan': r'\bSWANS?\b|SWAN UPP',
 'circus': r'CIRCUS',
 'magician': r'MAGICIAN|ILLUSIONIST|HYPNOTIST|HYPNOSIS',
 'puppet': r'PUPPET',
 'jester': r'JESTER',
 'wizard': r'WIZARD',
 'santa': r'\bSANTAS?\b|FATHER CHRISTMAS|REINDEER|\bELF\b|\bELVES\b|GROTTO',
 'panto': r'PANTOMIME|\bPANTO\b',
 'bouncy': r'BOUNCY',
 'ghost': r'\bGHOSTS?\b|HAUNTED|PARANORMAL',
 'zoo_farm': r'PETTING (ZOO|FARM)|ANIMAL ENCOUNTER|MOBILE FARM',
 'bagpipe': r'BAGPIPE',
 'ukulele': r'UKULELE|ACCORDION|KAZOO',
 'cheese': r'\bCHEESE\b|CHEESEMONG',
 'sausage': r'SAUSAGE',
 'crumpet': r'CRUMPET|\bSCONES?\b',
 'allotment': r'ALLOTMENT',
 'bunting': r'\bBUNTING\b',
 'knight_medieval': r'JOUST|MEDIEVAL',
 'clown': r'\bCLOWNS?\b',
 'stilt': r'\bSTILT',
 'fire_eat': r'FIRE EAT|FIRE BREATH|SWORD SWALLOW|ESCAPOLOG',
 'juggle': r'JUGGL',
 'punch_judy': r'PUNCH (AND|&) JUDY',
 'dinosaur': r'DINOSAUR|T-?REX',
 'unicorn': r'UNICORN',
 'mermaid': r'MERMAID',
 'pirate': r'PIRATE',
 'viking': r'VIKING',
 'druid': r'DRUID',
 'witch': r'\bWITCH(ES)?\b|WITCHCRAFT',
 'gnome': r'\bGNOMES?\b',
 'funfair': r'FUNFAIR|CAROUSEL|WALTZER|HELTER SKELTER',
 'maggot': r'MAGGOT',
 'snail': r'\bSNAILS?\b',
 'toad_frog': r'\bTOADS?\b|\bFROGS?\b',
 'newt': r'\bNEWTS?\b',
 'badger': r'\bBADGERS?\b',
 'squirrel': r'SQUIRREL',
 'otter': r'\bOTTERS?\b',
 'goat': r'\bGOATS?\b',
 'duck': r'\bDUCKS?\b',
 'sheep': r'\bSHEEP\b|SHEARING|SHEPHERD',
 'scarecrow': r'SCARECROW',
 'maypole': r'MAYPOLE',
 'wrestl': r'WRESTLING|WRESTLER',
 'elvis': r'\bELVIS\b',
 'lookalike': r'LOOKALIKE|LOOK-ALIKE|IMPERSONAT',
 'bell_ring': r'BELL ?RING|CAMPANOLOG|BELL ?FOUND',
 'organ': r'ORGAN (BUILDER|TUNER|TUNING)|ORGANIST',
 'thatching': r'THATCH',
 'dry_stone': r'DRY ?STONE',
 'hedgelay': r'HEDGE ?LAY',
 'blacksmith': r'BLACKSMITH|FARRIER',
 'chimney': r'CHIMNEY SWEEP',
 'coffin': r'COFFIN|CASKET',
 'lighthouse': r'LIGHTHOUSE',
 'archery': r'ARCHERY|LONGBOW',
 'cannon_hist': r'CANNON (COMPANY|HIRE)',
 'dungeon': r'DUNGEON',
 'ninja': r'\bNINJA\b',
 'karaoke': r'KARAOKE',
 'disco': r'\bDISCOS?\b|MOBILE DISCO',
 'clog': r'\bCLOG (DANC|MAK)',
 'trombone': r'TROMBONE|TUBA\b|EUPHONIUM',
 'harp': r'\bHARPIST\b',
 'steamengine': r'STEAM (ENGINE|RAILWAY|TRACTION)|TRACTION ENGINE',
 'windmill': r'WINDMILL|WATERMILL',
 'pigeon_race': r'PIGEON (RACING|FANCIER)',
 'rhubarb': r'RHUBARB',
 'turnip': r'TURNIP',
 'parsnip': r'PARSNIP',
 'gooseberry': r'GOOSEBERRY',
 'chutney': r'CHUTNEY',
 'toffee': r'TOFFEE',
 'fudge': r'\bFUDGE\b',
 'pudding': r'PUDDING',
 'trifle': r'TRIFLE',
 'custard': r'CUSTARD',
 'gravy': r'\bGRAVY\b',
 'kipper': r'KIPPER',
 'whelk': r'WHELK|COCKLE|WINKLE',
 'eel': r'\bEELS?\b',
 'ostrich': r'OSTRICH',
 'emu': r'\bEMUS?\b',
 'reptile': r'REPTILE',
 'butterfly_farm': r'BUTTERFLY (FARM|HOUSE|CONSERV)',
 'stick_insect': r'STICK INSECT',
 'dogpoo': r'DOG (WASTE|POO|FOUL)',
 'toilet': r'TOILET (HIRE|TWINNING)|PORTALOO|PORTA ?LOO',
 'knitting': r'KNITTING|CROCHET|YARN ?BOMB',
 'basket_weav': r'BASKET ?WEAV|BASKETRY|WICKERWORK',
 'corn_dolly': r'CORN DOLL',
 'gargoyle': r'GARGOYLE',
 'heraldry': r'HERALDRY|COLLEGE OF ARMS',
 'regalia': r'REGALIA|CIVIC ROBES',
 'mace': r'\bMACE (BEARER|REPAIR)',
 'wig': r'WIG MAK|WIGMAK',
 'flag': r'FLAGPOLE',
 'cuckoo': r'CUCKOO',
 'haggis': r'HAGGIS',
 'shortbread': r'SHORTBREAD',
 'marmalade': r'MARMALADE',
 'wombat': r'WOMBAT',
 'armadillo': r'ARMADILLO',
 'aardvark': r'AARDVARK',
 'walrus': r'WALRUS',
 'flamingo': r'FLAMINGO',
 'giraffe': r'GIRAFFE',
 'hippo': r'HIPPOPOTAM|\bHIPPO\b',
 'rhino_animal': r'RHINOCEROS',
 'camel': r'\bCAMELS?\b',
 'meerkat': r'MEERKAT',
 'sloth': r'\bSLOTHS?\b',
 'crab': r'\bCRABS?\b',
 'lobster': r'LOBSTER',
 'jellyfish': r'JELLYFISH',
 'whale': r'\bWHALES?\b',
 'dolphin': r'DOLPHIN',
 'seal_org': r'SEAL (SANCTUARY|RESCUE)',
 'puffin_org': r'PUFFIN(?!S? BOOKS)',
 'snake': r'\bSNAKES?\b',
 'spider_org': r'\bSPIDERS?\b',
 'worm_org': r'WORMER|WORM FARM|WORMERY',
 'sword': r'\bSWORDS?\b',
 'ye_olde': r'\bYE OLDE?\b',
 'wench': r'\bWENCH',
 'crier_misc': r'OYEZ',
}
out = open('name_candidates.csv', 'w', newline='', encoding='utf-8')
w = csv.writer(out)
w.writerow(['bucket', 'supplier_raw', 'n_txn', 'gbp_total', 'n_publishers', 'a_publisher'])
counts = {}
for r in rows:
    s = r['supplier_raw'].upper()
    for k, p in patterns.items():
        if re.search(p, s):
            w.writerow([k, r['supplier_raw'], r['n_txn'], r['gbp_total'], r['n_publishers'], r['a_publisher']])
            counts[k] = counts.get(k, 0) + 1
out.close()
for k in sorted(counts, key=counts.get, reverse=True):
    print(k, counts[k])
