import sqlite3
con = sqlite3.connect('C:/Users/domin/Documents/Open Data/analysis/spending/corpus.db')
cur = con.cursor()
W = "is_dup=0 AND supplier_raw<>''"

def rows(label, sql, args=()):
    print('===', label)
    for r in cur.execute(sql, args):
        print(r)
    print()

rows('Josephs Amazing Camels', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%AMAZING CAMELS%'")
rows('Real Reindeer', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%REAL REINDEER%'")
rows('Conwy Jester', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%CONWY JESTER%'")
rows('Ukulele Orchestra', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%UKULELE%'")
rows('Cosmic Sausages', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%COSMIC SAUSAGES%'")
rows('UK Hypnosis Academy', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%HYPNOSIS%'")
rows('ITV Text Santa', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%TEXT SANTA%'")
rows('Stallion and Unicorn', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%STALLION AND UNICORN%'")
rows('DINOSAUR TfGM', f"SELECT publisher, supplier_raw, ROUND(SUM(amount),2), COUNT(*), MIN(date), MAX(date), MIN(expense_type), MIN(source_file) FROM transactions WHERE {W} AND supplier_raw='DINOSAUR' GROUP BY publisher, supplier_raw")
rows('McCallum Bagpipes', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%MCCALLUM BAGPIPES%'")
rows('Walkers Shortbread', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%WALKERS SHORTBREAD%'")
rows('Flag and Bunting', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND (UPPER(supplier_raw) LIKE '%FLAG AND BUNTING%' OR UPPER(supplier_raw) LIKE '%KREATIVE BUNTING%')")
rows('MCC fortune tellers rows', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND UPPER(expense_type) LIKE '%FORTUNE TELLER%' ORDER BY amount DESC")
rows('MCC amusement parks/circus MoD', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND expense_type='Amusement Parks/Circus'")
rows('MCC disco FCDO summary', f"SELECT publisher, COUNT(*), ROUND(SUM(amount),2), MIN(date), MAX(date) FROM transactions WHERE {W} AND UPPER(expense_type) LIKE '%DISCO,NIGHTCLUB%' GROUP BY publisher")
rows('MCC dolphinarium rows', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND UPPER(expense_type) LIKE '%DOLPHINARIUM%' ORDER BY amount DESC")
rows('Portsmouth Lloyds 1M count', f"SELECT publisher, supplier_raw, COUNT(*), MIN(date), MAX(date) FROM transactions WHERE {W} AND amount=1000000 AND UPPER(supplier_raw) LIKE '%LLOYDS PHARMACY%' GROUP BY publisher, supplier_raw")
rows('Uttlesford Stansted 1M', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND publisher LIKE 'Uttlesford%' AND UPPER(supplier_raw) LIKE '%STANSTED AIRPORT%' AND amount>=500000")
rows('DWP Serco 1p count', f"SELECT publisher, supplier_raw, COUNT(*), MIN(date), MAX(date) FROM transactions WHERE {W} AND amount=0.01 AND UPPER(supplier_raw) LIKE '%SERCO%' GROUP BY publisher, supplier_raw")
rows('DHSC 1p rows all', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND publisher='Department of Health and Social Care' AND amount=0.01")
rows('Rushmoor Panto Expenditure summary', f"SELECT expense_type, COUNT(*), ROUND(SUM(amount),2), ROUND(MIN(amount),2), ROUND(MAX(amount),2), MIN(date), MAX(date) FROM transactions WHERE {W} AND publisher='Rushmoor Borough Council' AND expense_type LIKE '%Panto%' GROUP BY expense_type")
rows('Rushmoor Panto top suppliers', f"SELECT supplier_raw, COUNT(*), ROUND(SUM(amount),2) FROM transactions WHERE {W} AND publisher='Rushmoor Borough Council' AND expense_type LIKE '%Panto%' GROUP BY supplier_raw ORDER BY 3 DESC LIMIT 12")
rows('Organist lines', f"SELECT publisher, expense_type, COUNT(*), ROUND(SUM(amount),2), MIN(date), MAX(date) FROM transactions WHERE {W} AND (expense_type='Organist' OR expense_type='Organists Fees') GROUP BY publisher, expense_type")
rows('Swan sanctuary donation', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND UPPER(expense_type) LIKE '%SWAN SANCTUARY%'")
rows('Lord Lieutenants summary', f"SELECT publisher, expense_type, COUNT(*), ROUND(SUM(amount),2), MIN(date), MAX(date) FROM transactions WHERE {W} AND UPPER(expense_type) LIKE '%LORD LIEUTENANT%' GROUP BY publisher, expense_type")
rows('DCMS horseracing', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND (UPPER(expense_area) LIKE '%HORSERACING%')")
rows('DEFRA bat lures', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND (UPPER(expense_type) LIKE '%BAT LURE%' OR UPPER(expense_type) LIKE '%SONIC LURE%')")
rows('DEFRA quad bikes cattle', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND UPPER(expense_type) LIKE '%QUAD BIKES FOR CATTLE%'")
rows('Victoria Day Punch and Judy', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND UPPER(expense_type) LIKE '%PUNCH AND JUDY%'")
rows('Rushmoor Civic Regalia + Robes', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND expense_type IN ('Civic Regalia','Civic Robes')")
rows('Michaels Civic Robes rows', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%MICHAELS CIVIC ROBES%'")
rows('Falconry pest control rows', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%COUNTRYWIDE FALCONRY%'")
rows('Yoredale Birds of Prey', f"SELECT publisher, supplier_raw, ROUND(SUM(amount),2), COUNT(*), MIN(date), MAX(date), MIN(expense_type) FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%YOREDALE%' GROUP BY publisher, supplier_raw")
rows('Alpacas Peopleton Bristol', f"SELECT publisher, supplier_raw, ROUND(SUM(amount),2), COUNT(*), MIN(date), MAX(date), MIN(expense_type), MAX(expense_type) FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%ALPACAS PEOPLETON%' GROUP BY publisher, supplier_raw")
rows('Kellys Donkeys + South East Donkeys', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND (UPPER(supplier_raw) LIKE '%KELLY%DONKEY%' OR UPPER(supplier_raw) LIKE '%SOUTH EAST DONKEYS%')")
rows('Thirsk Yarnbombers', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%YARNBOMB%'")
rows('Cumberland wrestling', f"SELECT publisher, supplier_raw, amount, date, expense_type, expense_area, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%WESTMORLAND WRESTLING%'")
rows('Superslam wrestling', f"SELECT publisher, supplier_raw, ROUND(SUM(amount),2), COUNT(*), MIN(date), MAX(date), MIN(expense_type) FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%SUPERSLAM%' GROUP BY publisher, supplier_raw")
rows('DO NOT USE supplier', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND supplier_raw LIKE '%DO NOT USE%' LIMIT 20")
rows('REDACTED blacksmith', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND supplier_raw LIKE 'REDACTED T/A%'")
rows('Duck2Water phone number', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND supplier_raw LIKE 'DUCK-2-WATER%'")
rows('Ye Olde Friars', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%YE OLDE FRIARS%'")
rows('Grave digging Rushmoor', f"SELECT expense_type, COUNT(*), ROUND(SUM(amount),2), MIN(date), MAX(date) FROM transactions WHERE {W} AND publisher='Rushmoor Borough Council' AND expense_type LIKE '%Grave Digging%' GROUP BY expense_type")
rows('Sheep Dip Lane Academy', f"SELECT publisher, supplier_raw, ROUND(SUM(amount),2), COUNT(*), MIN(date), MAX(date) FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%SHEEP DIP%' GROUP BY publisher, supplier_raw")
rows('Eat That Frog', f"SELECT publisher, supplier_raw, ROUND(SUM(amount),2), COUNT(*) FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%EAT THAT FROG%' GROUP BY publisher, supplier_raw")
rows('Curious Hedgehogs Bristol', f"SELECT publisher, supplier_raw, ROUND(SUM(amount),2), COUNT(*), MIN(expense_type), MAX(expense_type) FROM transactions WHERE {W} AND supplier_raw='Curious Hedgehogs' GROUP BY publisher")
rows('Crafty Wizards Greenwich', f"SELECT publisher, supplier_raw, ROUND(SUM(amount),2), COUNT(*), MIN(expense_type), MAX(expense_type) FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%CRAFTY WIZARDS%' GROUP BY publisher")
rows('Pooley Sword MoD', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%POOLEY SWORD%'")
rows('Smiffys wigmakers', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%WIGMAKERS%'")
rows('Handspring Puppet', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%HANDSPRING PUPPET%'")
rows('Silent Disco King', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%SILENT DISCO KING%'")
rows('Stray Ferret', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%STRAY FERRET%'")
rows('London Taxidermy NHM', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%TAXIDERM%'")
rows('Great Grottos', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%GREAT GROTTOS%'")
rows('Berkshire Birds of Prey', f"SELECT publisher, supplier_raw, ROUND(SUM(amount),2), COUNT(*), MIN(date), MAX(date), MIN(expense_type) FROM transactions WHERE {W} AND UPPER(supplier_raw) LIKE '%BERKSHIRE BIRDS OF PREY%' GROUP BY publisher, supplier_raw")
rows('Cheltenham allotment water', f"SELECT publisher, supplier_raw, amount, date, expense_type, source_file FROM transactions WHERE {W} AND publisher LIKE 'Cheltenham%' AND UPPER(supplier_raw) LIKE '%HAYDEN ROAD ALLOTMENTS%'")
